sonar.projectKey=VanPhuHien_Test-FE-ELINGO
sonar.projectName=Elingo-Frontend
sonar.organization=vanphuhien

sonar.sources=src
sonar.tests=tests

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
