sonar.projectKey=VanPhuHien_Test-FE-ELINGO
sonar.projectName=Test-FE-ELINGO
sonar.organization=vanphuhien

sonar.sources=frontend/src
sonar.tests=frontend/tests

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
