name: Build Frontend & SonarQube

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/build.yml'
      - 'sonar-project.properties'
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
    paths:
      - 'frontend/**'
      - '.github/workflows/build.yml'
      - 'sonar-project.properties'

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies & Run Test Coverage
        working-directory: ./frontend
        run: |
          npm ci
          npm run test:coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: SonarQube Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}